// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Link(Done Till Step 6): https://www.prisma.io/docs/prisma-orm/add-to-existing-project/postgresql
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
